// <auto-generated />
using System;
using Eia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eia.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Eia.Data.Entities.ExtractionRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExtractionRuns");
                });

            modelBuilder.Entity("Eia.Data.Entities.NuclearOutage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CapacityMw")
                        .HasColumnType("REAL");

                    b.Property<int>("ExtractionRunId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OutageMw")
                        .HasColumnType("REAL");

                    b.Property<double?>("PercentOutage")
                        .HasColumnType("REAL");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionRunId");

                    b.HasIndex("Period")
                        .IsUnique();

                    b.ToTable("NuclearOutages");
                });

            modelBuilder.Entity("Eia.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Eia.Data.Entities.NuclearOutage", b =>
                {
                    b.HasOne("Eia.Data.Entities.ExtractionRun", "ExtractionRun")
                        .WithMany("NuclearOutages")
                        .HasForeignKey("ExtractionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtractionRun");
                });

            modelBuilder.Entity("Eia.Data.Entities.ExtractionRun", b =>
                {
                    b.Navigation("NuclearOutages");
                });
#pragma warning restore 612, 618
        }
    }
}
